### ISSUE TITLE
`./configure --enable-ksh` stills installs manual as `oksh`

### ISSUE THREAD

**Issue by gotroyb127** [ibara/oksh#55]
Hi again,
I am using this shell as `ksh` so I also install its manual page as `ksh`.

Currently `./configure --enable-ksh` only makes the executable named `ksh` instead of `oksh`
but the manual is installed as `oksh.1`.

Another weird thing I noticed is that `oksh.1` has a lot missing from `ksh.1`
(e.g. `pipefail` is not mentioned once in `oksh.1`.)

Beside that it seems to me that `./configure --enable-ksh` should also install the manual as `ksh.1`,
so I report it in case you didn't want that explicitly.

Thank you.

**Comment by ibara** [comment]
Are you sure about this? I just ran `./configure --enable-ksh && make && make install` and the manual page was installed as ksh.1. This is the expected behavior, since the Makefile line responsible for manual page installation is
```
install -c -m 644 oksh.1 ${DESTDIR}${MANDIR}/man1/${PROG}.1
```
${PROG} will be set to ksh if you used --enable-ksh with configure.

The manual page not being updated is my fault. I forgot to updated it. I'll do that now.

**Comment by ibara** [comment]
On second thought, I changed the command. Now it's
```
install -c -m 644 \$PROG}.1 ${DESTDIR}${MANDIR}/man1
```
which should definitely always work.

**Comment by gotroyb127** [comment]
With these changes, I think, the issue is closed.

Thank you again.
